name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix and Regenerate Gradle Wrapper
        run: |
          rm -rf gradle/wrapper/gradle-wrapper.jar
          gradle wrapper --gradle-version 9.3.1
          chmod +x ./gradlew

      - name: Build APK Debug
        run: ./gradlew assembleDebug
        
